// ============================================================
// マネータイプ診断 マスターデータ
// Google Sheetsから読み込む構造を維持しつつ、
// v1.0ではJSオブジェクトとしてハードコード
// ============================================================

const MONEY_DATA = {

  // ============================
  // 設問一覧
  // ============================
  questions: [
    {
      id: "Q1",
      text: "もし今日、100万円が手に入ったら？",
      choices: [
        { label: "①貯金する",     scores: { mamoru:2, fuyasu:0, ronri:1, chokkan:0, keikaku:1, chosen:0, anshin:2, jiyuu:0, shunyuKaizen:0, shisanKeisei:1 } },
        { label: "②一部投資する", scores: { mamoru:1, fuyasu:1, ronri:2, chokkan:0, keikaku:2, chosen:0, anshin:1, jiyuu:0, shunyuKaizen:0, shisanKeisei:2 } },
        { label: "③自己投資する", scores: { mamoru:0, fuyasu:2, ronri:0, chokkan:1, keikaku:0, chosen:2, anshin:0, jiyuu:1, shunyuKaizen:2, shisanKeisei:1 } },
        { label: "④体験に使う",   scores: { mamoru:0, fuyasu:1, ronri:0, chokkan:2, keikaku:0, chosen:1, anshin:0, jiyuu:2, shunyuKaizen:0, shisanKeisei:0 } },
      ]
    },
    {
      id: "Q2",
      text: "買い物のとき、どう決める？",
      choices: [
        { label: "①最安を探す",     scores: { mamoru:1, fuyasu:0, ronri:2, chokkan:0, keikaku:1, chosen:0, anshin:1, jiyuu:0, shunyuKaizen:0, shisanKeisei:0 } },
        { label: "②比較して決める", scores: { mamoru:1, fuyasu:1, ronri:2, chokkan:0, keikaku:2, chosen:0, anshin:1, jiyuu:0, shunyuKaizen:0, shisanKeisei:1 } },
        { label: "③必要なら即決",   scores: { mamoru:0, fuyasu:1, ronri:1, chokkan:0, keikaku:0, chosen:2, anshin:0, jiyuu:1, shunyuKaizen:1, shisanKeisei:0 } },
        { label: "④直感で決める",   scores: { mamoru:0, fuyasu:0, ronri:0, chokkan:2, keikaku:0, chosen:1, anshin:0, jiyuu:2, shunyuKaizen:0, shisanKeisei:0 } },
      ]
    },
    {
      id: "Q3",
      text: "あなたにとって「理想のお金の使い方」は？",
      choices: [
        { label: "①安心を作る",   scores: { mamoru:2, fuyasu:0, ronri:0, chokkan:0, keikaku:1, chosen:0, anshin:2, jiyuu:0, shunyuKaizen:0, shisanKeisei:0 } },
        { label: "②資産を育てる", scores: { mamoru:0, fuyasu:2, ronri:1, chokkan:0, keikaku:2, chosen:0, anshin:1, jiyuu:0, shunyuKaizen:0, shisanKeisei:2 } },
        { label: "③挑戦したい",   scores: { mamoru:0, fuyasu:2, ronri:0, chokkan:0, keikaku:0, chosen:2, anshin:0, jiyuu:2, shunyuKaizen:2, shisanKeisei:0 } },
        { label: "④人生を楽しむ", scores: { mamoru:0, fuyasu:1, ronri:0, chokkan:1, keikaku:0, chosen:1, anshin:0, jiyuu:2, shunyuKaizen:0, shisanKeisei:0 } },
      ]
    },
    {
      id: "Q4",
      text: "投資・副業を始めるとしたら？",
      choices: [
        { label: "①慎重に考える",   scores: { mamoru:2, fuyasu:0, ronri:1, chokkan:0, keikaku:2, chosen:0, anshin:2, jiyuu:0, shunyuKaizen:0, shisanKeisei:0 } },
        { label: "②勉強して始める", scores: { mamoru:1, fuyasu:1, ronri:2, chokkan:0, keikaku:2, chosen:0, anshin:1, jiyuu:0, shunyuKaizen:0, shisanKeisei:2 } },
        { label: "③少額で試す",     scores: { mamoru:0, fuyasu:2, ronri:1, chokkan:0, keikaku:0, chosen:2, anshin:0, jiyuu:1, shunyuKaizen:1, shisanKeisei:1 } },
        { label: "④まず飛び込む",   scores: { mamoru:0, fuyasu:2, ronri:0, chokkan:2, keikaku:0, chosen:2, anshin:0, jiyuu:2, shunyuKaizen:2, shisanKeisei:0 } },
      ]
    },
    {
      id: "Q5",
      text: "ボーナスが出たら、どう使う？",
      choices: [
        { label: "①貯蓄する",       scores: { mamoru:2, fuyasu:0, ronri:0, chokkan:0, keikaku:1, chosen:0, anshin:2, jiyuu:0, shunyuKaizen:0, shisanKeisei:1 } },
        { label: "②投資する",       scores: { mamoru:0, fuyasu:2, ronri:2, chokkan:0, keikaku:2, chosen:0, anshin:1, jiyuu:0, shunyuKaizen:0, shisanKeisei:2 } },
        { label: "③自己投資する",   scores: { mamoru:0, fuyasu:2, ronri:0, chokkan:1, keikaku:0, chosen:2, anshin:0, jiyuu:1, shunyuKaizen:2, shisanKeisei:0 } },
        { label: "④欲しい物を買う", scores: { mamoru:0, fuyasu:1, ronri:0, chokkan:2, keikaku:0, chosen:1, anshin:0, jiyuu:2, shunyuKaizen:0, shisanKeisei:0 } },
      ]
    },
    {
      id: "Q6",
      text: "あなたにとって「理想の働き方」は？",
      choices: [
        { label: "①安定して働く",   scores: { mamoru:2, fuyasu:0, ronri:1, chokkan:0, keikaku:1, chosen:0, anshin:2, jiyuu:0, shunyuKaizen:0, shisanKeisei:0 } },
        { label: "②専門性を高める", scores: { mamoru:1, fuyasu:1, ronri:2, chokkan:0, keikaku:2, chosen:0, anshin:1, jiyuu:0, shunyuKaizen:1, shisanKeisei:1 } },
        { label: "③収入を伸ばす",   scores: { mamoru:0, fuyasu:2, ronri:1, chokkan:0, keikaku:0, chosen:2, anshin:0, jiyuu:1, shunyuKaizen:2, shisanKeisei:1 } },
        { label: "④自由に働く",     scores: { mamoru:0, fuyasu:1, ronri:0, chokkan:2, keikaku:0, chosen:2, anshin:0, jiyuu:2, shunyuKaizen:1, shisanKeisei:0 } },
      ]
    },
    {
      id: "Q7",
      text: "一番共感できるのはどれ？",
      choices: [
        { label: "①失敗したくない", scores: { mamoru:2, fuyasu:0, ronri:1, chokkan:0, keikaku:2, chosen:0, anshin:2, jiyuu:0, shunyuKaizen:0, shisanKeisei:0 } },
        { label: "②納得して動く",   scores: { mamoru:1, fuyasu:0, ronri:2, chokkan:0, keikaku:2, chosen:0, anshin:1, jiyuu:0, shunyuKaizen:0, shisanKeisei:1 } },
        { label: "③成長したい",     scores: { mamoru:0, fuyasu:2, ronri:1, chokkan:0, keikaku:0, chosen:2, anshin:0, jiyuu:1, shunyuKaizen:2, shisanKeisei:1 } },
        { label: "④楽しそうならやる", scores: { mamoru:0, fuyasu:1, ronri:0, chokkan:2, keikaku:0, chosen:2, anshin:0, jiyuu:2, shunyuKaizen:0, shisanKeisei:0 } },
      ]
    },
    {
      id: "Q8",
      text: "友人から新しい投資や副業を勧められたら？",
      choices: [
        { label: "①様子を見る",         scores: { mamoru:2, fuyasu:0, ronri:1, chokkan:0, keikaku:2, chosen:0, anshin:2, jiyuu:0, shunyuKaizen:0, shisanKeisei:0 } },
        { label: "②調べて判断する",     scores: { mamoru:1, fuyasu:1, ronri:2, chokkan:0, keikaku:2, chosen:0, anshin:1, jiyuu:0, shunyuKaizen:0, shisanKeisei:2 } },
        { label: "③少額で試す",         scores: { mamoru:0, fuyasu:2, ronri:1, chokkan:0, keikaku:0, chosen:2, anshin:0, jiyuu:1, shunyuKaizen:1, shisanKeisei:1 } },
        { label: "④ワクワクするかで決断", scores: { mamoru:0, fuyasu:1, ronri:0, chokkan:2, keikaku:0, chosen:2, anshin:0, jiyuu:2, shunyuKaizen:1, shisanKeisei:0 } },
      ]
    },
    {
      id: "Q9",
      text: "今、一番近い気持ちは？",
      tiebreaker: true,
      choices: [
        { label: "①支出を減らしたい", scores: { mamoru:0, fuyasu:0, ronri:0, chokkan:0, keikaku:0, chosen:0, anshin:0, jiyuu:0, shunyuKaizen:0, shisanKeisei:0 } },
        { label: "②貯金を増やしたい", scores: { mamoru:0, fuyasu:0, ronri:0, chokkan:0, keikaku:0, chosen:0, anshin:0, jiyuu:0, shunyuKaizen:0, shisanKeisei:1 } },
        { label: "③収入を増やしたい", scores: { mamoru:0, fuyasu:0, ronri:0, chokkan:0, keikaku:0, chosen:0, anshin:0, jiyuu:0, shunyuKaizen:2, shisanKeisei:0 } },
        { label: "④将来が不安",       scores: { mamoru:0, fuyasu:0, ronri:0, chokkan:0, keikaku:0, chosen:0, anshin:0, jiyuu:0, shunyuKaizen:1, shisanKeisei:1 } },
      ]
    },
    {
      id: "Q10",
      text: "5年後の理想を選ぶなら？",
      tiebreaker: true,
      choices: [
        { label: "①家計を安定させたい", scores: { mamoru:0, fuyasu:0, ronri:0, chokkan:0, keikaku:0, chosen:0, anshin:0, jiyuu:0, shunyuKaizen:0, shisanKeisei:1 } },
        { label: "②資産形成したい",     scores: { mamoru:0, fuyasu:0, ronri:0, chokkan:0, keikaku:0, chosen:0, anshin:0, jiyuu:0, shunyuKaizen:0, shisanKeisei:2 } },
        { label: "③キャリアアップしたい", scores: { mamoru:0, fuyasu:0, ronri:0, chokkan:0, keikaku:0, chosen:0, anshin:0, jiyuu:0, shunyuKaizen:2, shisanKeisei:0 } },
        { label: "④人生を楽しみたい",   scores: { mamoru:0, fuyasu:0, ronri:0, chokkan:0, keikaku:0, chosen:0, anshin:0, jiyuu:2, shunyuKaizen:1, shisanKeisei:0 } },
      ]
    },
  ],

  // ============================
  // 16タイプ定義
  // axes: [守る/増やす, 論理/直感, 計画/挑戦, 安心/自由]
  // ============================
  types: [
    {
      id: "turtle",
      name: "資産防衛タートル",
      emoji: "🐢",
      axes: { mamoru:true, ronri:true, keikaku:true, anshin:true },
      axisLabel: "守る・論理・計画・安心",
      catchcopy: "堅実に未来を築く守護者",
      subcopy: "焦らず、一歩ずつ積み重ねる人",
      summary: "安心を資産に変えるタイプ",
      description: "あなたは大きな成功よりも、失敗しないことを大切にするタイプです。流行や周囲の声に流されず、自分の価値観を信じて着実に前へ進みます。派手さはありませんが、長い目で見ると大きな成果を残す力を持っています。",
      forYou: "周りと比べる必要はありません。あなたの強みは続ける力です。",
      money: "お金は未来の安心を作るもの",
      work: "堅実に信頼を積み重ねる",
      love: "将来を安心して語れる相手を求める",
      strengths: ["継続力", "堅実さ", "責任感"],
      weaknesses: ["慎重すぎる", "挑戦を避けやすい"],
      failures: "考えているうちに機会を逃す",
      growth: "小さな挑戦を習慣にする",
      stress: "一人で抱え込む",
      successReason: "長期目線で判断できる",
      failureScene: "リスクを恐れすぎる",
      goodMatch: "覇道ライオン",
      goodMatchReason: "行動力と計画力が補い合える",
      badMatch: "革命ユニコーン",
      badMatchReason: "価値観の違いに戸惑いやすい",
      message: "あなたの積み重ねは、未来で大きな財産になります。",
      luckyAction: "1年後の目標を書く",
      luckyColor: "ネイビー",
      luckyItem: "革の手帳",
      snsText: "私は「資産防衛タートル🐢」でした！",
      ogpCatch: "コツコツ積み上げる未来設計士",
      resultTitle: "あなたは「資産防衛タートル」",
      resultLead: "焦らず進むその姿勢が、未来を守る力になります。",
      colorMain: "#1a237e",
      colorSub: "#283593",
      image: "turtle.png",
      ogpImage: "ogp_turtle.png",
    },
    {
      id: "penguin",
      name: "悠々ペンギン",
      emoji: "🐧",
      axes: { mamoru:true, ronri:true, keikaku:true, anshin:false },
      axisLabel: "守る・論理・計画・自由",
      catchcopy: "楽しみながら備える達人",
      subcopy: "我慢しすぎない賢いバランサー",
      summary: "人生もお金も両方楽しむタイプ",
      description: "あなたは将来への備えも、今を楽しむことも大切にできる人です。極端な節約も浪費もしないため、周囲から安心感を持たれやすい存在です。自分らしいペースで豊かさを育てていけます。",
      forYou: "無理なく続けられることが、あなたの最大の武器です。",
      money: "お金は人生を豊かにする道具",
      work: "安定と柔軟さを両立する",
      love: "自然体でいられる関係を好む",
      strengths: ["バランス感覚", "継続力", "安定感"],
      weaknesses: ["現状維持になりやすい", "大勝負が苦手"],
      failures: "チャンスを見送りがち",
      growth: "たまには思い切って挑戦する",
      stress: "周囲に合わせすぎる",
      successReason: "計画的に積み上げられる",
      failureScene: "慎重になりすぎる",
      goodMatch: "理想ドラゴン",
      goodMatchReason: "夢を現実へ近づけられる",
      badMatch: "独立フェニックス",
      badMatchReason: "ペースの違いに疲れやすい",
      message: "楽しみながら続けることが、一番の近道です。",
      luckyAction: "新しい趣味を始める",
      luckyColor: "ターコイズ",
      luckyItem: "お気に入りのマグカップ",
      snsText: "私は「悠々ペンギン🐧」でした！",
      ogpCatch: "人生を楽しむマネーバランサー",
      resultTitle: "あなたは「悠々ペンギン」",
      resultLead: "安心も楽しさも大切にできる、賢いタイプです。",
      colorMain: "#00695c",
      colorSub: "#00897b",
      image: "penguin.png",
      ogpImage: "ogp_penguin.png",
    },
    {
      id: "fox",
      name: "戦略フォックス",
      emoji: "🦊",
      axes: { mamoru:true, ronri:true, keikaku:false, anshin:true },
      axisLabel: "守る・論理・挑戦・安心",
      catchcopy: "勝率を計算する参謀",
      subcopy: "情報を武器に未来を切り拓く人",
      summary: "考えて勝つ頭脳派タイプ",
      description: "あなたは感情だけで動かず、情報を集めて最善策を探すタイプです。大きな失敗は少なく、冷静な判断で周囲から頼られることも多いでしょう。知識を行動に変えたとき、本当の力を発揮します。",
      forYou: "あなたの考える力は、大きな武器になります。",
      money: "お金は効率よく活かすもの",
      work: "分析して成果を出す",
      love: "相手をよく知ってから心を開く",
      strengths: ["分析力", "情報収集力", "判断力"],
      weaknesses: ["考えすぎる", "慎重すぎる"],
      failures: "完璧を求めて動けなくなる",
      growth: "70点でも行動する",
      stress: "情報を集め続ける",
      successReason: "冷静に判断できる",
      failureScene: "決断が遅れやすい",
      goodMatch: "創造オクトパス",
      goodMatchReason: "アイデアを現実に変えられる",
      badMatch: "のんびりパンダ",
      badMatchReason: "価値観のズレを感じやすい",
      message: "知識は、動いた瞬間に価値へ変わります。",
      luckyAction: "新しいことを1つ試す",
      luckyColor: "グリーン",
      luckyItem: "ノートPC",
      snsText: "私は「戦略フォックス🦊」でした！",
      ogpCatch: "頭脳で未来を切り拓く参謀",
      resultTitle: "あなたは「戦略フォックス」",
      resultLead: "冷静な判断力が、未来を切り拓く武器になります。",
      colorMain: "#2e7d32",
      colorSub: "#388e3c",
      image: "fox.png",
      ogpImage: "ogp_fox.png",
    },
    {
      id: "wolf",
      name: "開拓ウルフ",
      emoji: "🐺",
      axes: { mamoru:true, ronri:true, keikaku:false, anshin:false },
      axisLabel: "守る・論理・挑戦・自由",
      catchcopy: "自分の道を切り拓く冒険者",
      subcopy: "自由を求める孤高のチャレンジャー",
      summary: "自立心で未来を作るタイプ",
      description: "あなたは周囲に流されず、自分の信じる道を歩くタイプです。責任も自由も引き受け、自ら環境を変えていく強さを持っています。新しい世界へ飛び込む勇気が、人生を大きく動かします。",
      forYou: "あなたには、自分だけの道を歩く力があります。",
      money: "お金は自由を得るための手段",
      work: "裁量の大きい環境で力を発揮する",
      love: "依存しない対等な関係を好む",
      strengths: ["行動力", "独立心", "決断力"],
      weaknesses: ["人を頼るのが苦手", "孤立しやすい"],
      failures: "全部一人で抱え込む",
      growth: "仲間を信頼する",
      stress: "一人になろうとする",
      successReason: "行動が成果につながりやすい",
      failureScene: "勢いで突き進みやすい",
      goodMatch: "調和ディアー",
      goodMatchReason: "心の支えになってくれる",
      badMatch: "資産防衛タートル",
      badMatchReason: "慎重さを窮屈に感じやすい",
      message: "あなたが切り拓く道は、誰かの希望にもなります。",
      luckyAction: "信頼できる人に相談する",
      luckyColor: "ダークレッド",
      luckyItem: "アウトドアギア",
      snsText: "私は「開拓ウルフ🐺」でした！",
      ogpCatch: "自由を掴む孤高の冒険者",
      resultTitle: "あなたは「開拓ウルフ」",
      resultLead: "誰にも真似できない、自分だけの未来を歩む人です。",
      colorMain: "#b71c1c",
      colorSub: "#c62828",
      image: "wolf.png",
      ogpImage: "ogp_wolf.png",
    },
    {
      id: "raccoon",
      name: "ひらめきラクーン",
      emoji: "🦝",
      axes: { mamoru:true, ronri:false, keikaku:true, anshin:true },
      axisLabel: "守る・直感・計画・安心",
      catchcopy: "感性で幸せを見つける表現者",
      subcopy: "心が動くものを大切にする人",
      summary: "感性を大切に人生を彩るタイプ",
      description: "あなたは理屈よりも、「好き」「心地いい」という感覚を大切にする人です。人の気持ちを理解する力があり、自然と周囲を癒やします。その優しさと感性は、多くの人を惹きつける魅力になります。",
      forYou: "あなたの感性は、誰かを笑顔にする才能です。",
      money: "お金は心を豊かにするためのもの",
      work: "人を支える仕事や表現活動で輝く",
      love: "気持ちのつながりを最優先する",
      strengths: ["感受性", "共感力", "発想力"],
      weaknesses: ["感情に流されやすい", "優柔不断"],
      failures: "勢いで決断してしまう",
      growth: "一晩考えてから決める",
      stress: "一人で落ち込みやすい",
      successReason: "人との縁を広げられる",
      failureScene: "気分で使いすぎる",
      goodMatch: "知略オウル",
      goodMatchReason: "感性と知性が補い合える",
      badMatch: "戦略フォックス",
      badMatchReason: "合理性に冷たさを感じやすい",
      message: "その優しさは、かけがえのない才能です。",
      luckyAction: "好きなことを書き出す",
      luckyColor: "ラベンダー",
      luckyItem: "アロマキャンドル",
      snsText: "私は「ひらめきラクーン🦝」でした！",
      ogpCatch: "感性で未来を彩る表現者",
      resultTitle: "あなたは「ひらめきラクーン」",
      resultLead: "あなたの優しさと感性は、大きな魅力です。",
      colorMain: "#6a1b9a",
      colorSub: "#7b1fa2",
      image: "raccoon.png",
      ogpImage: "ogp_raccoon.png",
    },
    {
      id: "deer",
      name: "調和ディアー",
      emoji: "🦌",
      axes: { mamoru:true, ronri:false, keikaku:true, anshin:false },
      axisLabel: "守る・直感・計画・自由",
      catchcopy: "みんなの幸せを願うサポーター",
      subcopy: "人との絆を何より大切にする人",
      summary: "支え合いを大切にするタイプ",
      description: "あなたは自分だけでなく、周りの人の幸せも考えられる人です。誰かの役に立てることに喜びを感じ、自然と信頼を集めます。人とのつながりが、あなたの人生を豊かにしていくでしょう。",
      forYou: "あなたの優しさは、周りを安心させています。",
      money: "お金は人との縁を育てるもの",
      work: "チームで力を発揮する",
      love: "安心できる関係を築く",
      strengths: ["思いやり", "協調性", "信頼感"],
      weaknesses: ["遠慮しすぎる", "断るのが苦手"],
      failures: "人のために使いすぎる",
      growth: "自分を優先する日を作る",
      stress: "我慢してしまう",
      successReason: "人脈に恵まれやすい",
      failureScene: "頼まれると断れない",
      goodMatch: "開拓ウルフ",
      goodMatchReason: "お互いに足りない部分を補える",
      badMatch: "革命ユニコーン",
      badMatchReason: "変化に振り回されやすい",
      message: "誰かを大切にするように、自分も大切にしてください。",
      luckyAction: "感謝を言葉にする",
      luckyColor: "ライトグリーン",
      luckyItem: "観葉植物",
      snsText: "私は「調和ディアー🦌」でした！",
      ogpCatch: "人との絆を育てるサポーター",
      resultTitle: "あなたは「調和ディアー」",
      resultLead: "あなたの優しさは、人を惹きつける力になります。",
      colorMain: "#558b2f",
      colorSub: "#689f38",
      image: "deer.png",
      ogpImage: "ogp_deer.png",
    },
    {
      id: "cat",
      name: "自由キャット",
      emoji: "🐈",
      axes: { mamoru:true, ronri:false, keikaku:false, anshin:true },
      axisLabel: "守る・直感・挑戦・安心",
      catchcopy: "好きなことに一直線な探求者",
      subcopy: "自分らしさを何より大切にする人",
      summary: "好きを力に変えるタイプ",
      description: "あなたは周りに合わせるより、自分が納得できる生き方を大切にします。好きな分野では驚くほど集中力を発揮し、自分だけの価値を生み出せる人です。",
      forYou: "好きなことは、あなたの才能の入り口です。",
      money: "お金は自分らしさを実現するもの",
      work: "裁量が大きい環境で活躍する",
      love: "束縛のない関係を好む",
      strengths: ["好奇心", "個性", "集中力"],
      weaknesses: ["飽きっぽい", "優先順位がぶれる"],
      failures: "好きなものに使いすぎる",
      growth: "目標を数字で決める",
      stress: "一人の時間が欲しくなる",
      successReason: "好きなことで努力を続けられる",
      failureScene: "計画性を忘れやすい",
      goodMatch: "未来ドルフィン",
      goodMatchReason: "自由と計画が良いバランスになる",
      badMatch: "資産防衛タートル",
      badMatchReason: "慎重さを窮屈に感じやすい",
      message: "あなたらしさは、誰にも真似できない武器です。",
      luckyAction: "新しい趣味に挑戦する",
      luckyColor: "オレンジ",
      luckyItem: "ワイヤレスイヤホン",
      snsText: "私は「自由キャット🐈」でした！",
      ogpCatch: "好きを追いかける自由人",
      resultTitle: "あなたは「自由キャット」",
      resultLead: "あなたの個性は、未来を切り拓く力になります。",
      colorMain: "#e65100",
      colorSub: "#f57c00",
      image: "cat.png",
      ogpImage: "ogp_cat.png",
    },
    {
      id: "panda",
      name: "のんびりパンダ",
      emoji: "🐼",
      axes: { mamoru:true, ronri:false, keikaku:false, anshin:false },
      axisLabel: "守る・直感・挑戦・自由",
      catchcopy: "肩の力を抜いて生きる達人",
      subcopy: "マイペースに幸せを見つける人",
      summary: "自然体で人生を楽しむタイプ",
      description: "あなたは競争よりも、自分らしい幸せを大切にする人です。無理をしない生き方が、結果的に周囲を安心させています。あなたの穏やかさは、多くの人の支えになります。",
      forYou: "焦らなくても、あなたにはあなたのペースがあります。",
      money: "お金は楽しく生きるためのもの",
      work: "無理なく続けられる環境向き",
      love: "一緒にいて安心できる関係を好む",
      strengths: ["柔軟性", "楽観性", "親しみやすさ"],
      weaknesses: ["後回しにしやすい", "危機感が薄くなる"],
      failures: "気づいたらお金が減っている",
      growth: "小さな習慣を作る",
      stress: "現実逃避したくなる",
      successReason: "長く続ける力がある",
      failureScene: "管理を面倒に感じる",
      goodMatch: "戦略フォックス",
      goodMatchReason: "管理面を支えてくれる",
      badMatch: "覇道ライオン",
      badMatchReason: "ペースの違いを感じやすい",
      message: "あなたの自然体な魅力は、周りを和ませています。",
      luckyAction: "家計を5分だけ見直す",
      luckyColor: "クリームイエロー",
      luckyItem: "お気に入りのクッション",
      snsText: "私は「のんびりパンダ🐼」でした！",
      ogpCatch: "マイペースに幸せを育てる人",
      resultTitle: "あなたは「のんびりパンダ」",
      resultLead: "あなたらしいペースが、一番の強みです。",
      colorMain: "#f9a825",
      colorSub: "#fbc02d",
      image: "panda.png",
      ogpImage: "ogp_panda.png",
    },
    {
      id: "dolphin",
      name: "未来ドルフィン",
      emoji: "🐬",
      axes: { mamoru:false, ronri:true, keikaku:true, anshin:true },
      axisLabel: "増やす・論理・計画・安心",
      catchcopy: "未来を見据える資産ビルダー",
      subcopy: "小さな積み重ねで未来を変える人",
      summary: "未来への選択肢を増やすタイプ",
      description: "あなたは目先の利益よりも、将来の安心や成長を大切にするタイプです。流行に流されず、自分なりの考えを持って一歩ずつ積み重ねていきます。派手さはなくても、長い時間を味方につけられる人です。",
      forYou: "焦らなくても大丈夫。あなたの歩みは着実に未来へつながっています。",
      money: "お金は未来の選択肢を増やすもの",
      work: "長期的な視点で成果を積み上げる",
      love: "信頼関係をゆっくり育てる",
      strengths: ["計画性", "継続力", "冷静さ"],
      weaknesses: ["慎重になりやすい", "変化が苦手"],
      failures: "チャンスを見送りがち",
      growth: "まず小さく始めてみる",
      stress: "不安を一人で抱えやすい",
      successReason: "長期目線で資産を育てられる",
      failureScene: "即効性を求めすぎると疲れる",
      goodMatch: "自由キャット",
      goodMatchReason: "自由な発想が刺激になる",
      badMatch: "理想ドラゴン",
      badMatchReason: "夢が大きすぎて振り回されやすい",
      message: "積み重ねは、必ず未来の自分を助けてくれます。",
      luckyAction: "5年後の目標を書き出す",
      luckyColor: "スカイブルー",
      luckyItem: "腕時計",
      snsText: "私は「未来ドルフィン🐬」でした！",
      ogpCatch: "未来を育てる長期投資家",
      resultTitle: "あなたは「未来ドルフィン」",
      resultLead: "コツコツ積み上げる力が、未来を大きく変えていきます。",
      colorMain: "#0277bd",
      colorSub: "#0288d1",
      image: "dolphin.png",
      ogpImage: "ogp_dolphin.png",
    },
    {
      id: "owl",
      name: "知略オウル",
      emoji: "🦉",
      axes: { mamoru:false, ronri:true, keikaku:true, anshin:false },
      axisLabel: "増やす・論理・計画・自由",
      catchcopy: "知識を武器にする分析家",
      subcopy: "学び続けることで未来を切り拓く人",
      summary: "知性で価値を生み出すタイプ",
      description: "あなたは納得してから動きたいタイプです。知識や経験を積み重ねることに喜びを感じ、誰よりも深く物事を理解しようとします。学びを行動へ変えたとき、大きな力を発揮します。",
      forYou: "知識は、あなたにしか持てない財産です。",
      money: "お金は知識で育てるもの",
      work: "専門性を高めるほど力を発揮する",
      love: "価値観が合う相手を大切にする",
      strengths: ["分析力", "学習力", "探究心"],
      weaknesses: ["勉強だけで終わりやすい", "考えすぎる"],
      failures: "行動が遅れる",
      growth: "完璧を目指しすぎない",
      stress: "情報を集め続ける",
      successReason: "冷静な判断ができる",
      failureScene: "決断を先送りしやすい",
      goodMatch: "ひらめきラクーン",
      goodMatchReason: "感性と知性が補い合える",
      badMatch: "天空イーグル",
      badMatchReason: "勢いについていけない",
      message: "学びを行動に変えた瞬間、未来が動き出します。",
      luckyAction: "新しい本を読む",
      luckyColor: "パープル",
      luckyItem: "万年筆",
      snsText: "私は「知略オウル🦉」でした！",
      ogpCatch: "知識で未来を切り拓く賢者",
      resultTitle: "あなたは「知略オウル」",
      resultLead: "あなたの知識は、大きな可能性を秘めています。",
      colorMain: "#4527a0",
      colorSub: "#512da8",
      image: "owl.png",
      ogpImage: "ogp_owl.png",
    },
    {
      id: "lion",
      name: "覇道ライオン",
      emoji: "🦁",
      axes: { mamoru:false, ronri:true, keikaku:false, anshin:true },
      axisLabel: "増やす・論理・挑戦・安心",
      catchcopy: "結果を掴みにいくリーダー",
      subcopy: "行動で未来を切り拓く王者",
      summary: "挑戦で可能性を広げるタイプ",
      description: "あなたは高い目標を掲げ、自分の力で未来を変えていくタイプです。責任感が強く、人を引っ張る力があります。成功だけでなく、挑戦する姿そのものが周囲に影響を与えています。",
      forYou: "あなたの行動力は、多くの人の希望になります。",
      money: "お金は可能性を広げる力",
      work: "先頭に立って成果を出す",
      love: "支え合える関係を求める",
      strengths: ["実行力", "決断力", "統率力"],
      weaknesses: ["強引になりやすい", "負けず嫌い"],
      failures: "勢いで突き進む",
      growth: "人の意見を聞く時間を作る",
      stress: "責任を背負い込みやすい",
      successReason: "チャンスを掴む力がある",
      failureScene: "守りを忘れやすい",
      goodMatch: "資産防衛タートル",
      goodMatchReason: "守りと攻めの理想形",
      badMatch: "のんびりパンダ",
      badMatchReason: "スピード感が合わない",
      message: "挑戦する姿勢は、未来を変える原動力です。",
      luckyAction: "目標を周囲に宣言する",
      luckyColor: "ゴールド",
      luckyItem: "革靴",
      snsText: "私は「覇道ライオン🦁」でした！",
      ogpCatch: "未来を切り拓く挑戦者",
      resultTitle: "あなたは「覇道ライオン」",
      resultLead: "あなたの行動力は、新しい景色を見せてくれます。",
      colorMain: "#f57f17",
      colorSub: "#f9a825",
      image: "lion.png",
      ogpImage: "ogp_lion.png",
    },
    {
      id: "eagle",
      name: "天空イーグル",
      emoji: "🦅",
      axes: { mamoru:false, ronri:true, keikaku:false, anshin:false },
      axisLabel: "増やす・論理・挑戦・自由",
      catchcopy: "大空を目指す挑戦者",
      subcopy: "限界の先を目指す冒険家",
      summary: "夢に向かって飛び続けるタイプ",
      description: "あなたは新しい世界を見ることに喜びを感じるタイプです。変化や挑戦を恐れず、自分の可能性を信じて飛び込みます。その大胆さが、人生を大きく変える武器になります。",
      forYou: "あなたの勇気は、未来を切り拓く翼です。",
      money: "お金は夢への燃料",
      work: "挑戦できる環境で輝く",
      love: "刺激のある関係を好む",
      strengths: ["挑戦力", "決断力", "行動力"],
      weaknesses: ["リスクを軽く見がち", "飽きやすい"],
      failures: "勢いだけで動く",
      growth: "立ち止まって振り返る",
      stress: "次の刺激を探し続ける",
      successReason: "大きな成果を掴みやすい",
      failureScene: "計画不足で失敗しやすい",
      goodMatch: "知略オウル",
      goodMatchReason: "冷静さが挑戦を支えてくれる",
      badMatch: "資産防衛タートル",
      badMatchReason: "慎重さを窮屈に感じやすい",
      message: "あなたには、まだ見ぬ景色を見つける力があります。",
      luckyAction: "新しい場所へ出かける",
      luckyColor: "ロイヤルブルー",
      luckyItem: "旅行バッグ",
      snsText: "私は「天空イーグル🦅」でした！",
      ogpCatch: "夢へ飛び立つチャレンジャー",
      resultTitle: "あなたは「天空イーグル」",
      resultLead: "その勇気が、人生を大きく変えていきます。",
      colorMain: "#1565c0",
      colorSub: "#1976d2",
      image: "eagle.png",
      ogpImage: "ogp_eagle.png",
    },
    {
      id: "octopus",
      name: "創造オクトパス",
      emoji: "🐙",
      axes: { mamoru:false, ronri:false, keikaku:true, anshin:true },
      axisLabel: "増やす・直感・計画・安心",
      catchcopy: "アイデアを形にするクリエイター",
      subcopy: "柔軟な発想で価値を生み出す人",
      summary: "個性を武器にするタイプ",
      description: "あなたは普通とは違う視点で物事を見る力を持っています。人が気づかない価値を見つけ、形にする才能があります。個性を信じることで大きく成長できます。",
      forYou: "あなたの発想は、世界を少し面白くします。",
      money: "お金は価値を生み出す材料",
      work: "企画や制作で力を発揮する",
      love: "個性を認め合える関係を好む",
      strengths: ["創造力", "柔軟性", "適応力"],
      weaknesses: ["集中が散りやすい", "迷いやすい"],
      failures: "手を広げすぎる",
      growth: "優先順位を決める",
      stress: "考え事に没頭する",
      successReason: "新しい価値を生み出せる",
      failureScene: "途中で飽きやすい",
      goodMatch: "戦略フォックス",
      goodMatchReason: "発想を形にしてくれる",
      badMatch: "覇道ライオン",
      badMatchReason: "成果主義に疲れやすい",
      message: "あなたの個性は、誰にも真似できません。",
      luckyAction: "思いつきをメモする",
      luckyColor: "エメラルドグリーン",
      luckyItem: "スケッチブック",
      snsText: "私は「創造オクトパス🐙」でした！",
      ogpCatch: "個性で未来を創るクリエイター",
      resultTitle: "あなたは「創造オクトパス」",
      resultLead: "その発想力は、大きな可能性を秘めています。",
      colorMain: "#00695c",
      colorSub: "#00796b",
      image: "octopus.png",
      ogpImage: "ogp_octopus.png",
    },
    {
      id: "dragon",
      name: "理想ドラゴン",
      emoji: "🐉",
      axes: { mamoru:false, ronri:false, keikaku:true, anshin:false },
      axisLabel: "増やす・直感・計画・自由",
      catchcopy: "大きな夢を描くビジョナリー",
      subcopy: "理想を信じて未来を描く人",
      summary: "夢を現実に変えるタイプ",
      description: "あなたは現状に満足せず、もっと大きな未来を思い描く人です。人を惹きつける理想と情熱を持っており、その姿勢が周囲を動かします。",
      forYou: "夢を見る力は、未来を変える力です。",
      money: "お金は夢を叶える翼",
      work: "未来を描く役割で力を発揮する",
      love: "一緒に夢を語れる相手を求める",
      strengths: ["発信力", "構想力", "情熱"],
      weaknesses: ["現実を忘れやすい", "理想を追いすぎる"],
      failures: "計画が追いつかない",
      growth: "小さな目標を作る",
      stress: "理想とのギャップに悩む",
      successReason: "大きな成果を生みやすい",
      failureScene: "足元がおろそかになる",
      goodMatch: "悠々ペンギン",
      goodMatchReason: "現実とのバランスを取ってくれる",
      badMatch: "未来ドルフィン",
      badMatchReason: "慎重さに焦りを感じやすい",
      message: "あなたの夢は、誰かの希望にもなります。",
      luckyAction: "夢ノートを作る",
      luckyColor: "ワインレッド",
      luckyItem: "星空の雑貨",
      snsText: "私は「理想ドラゴン🐉」でした！",
      ogpCatch: "夢で未来を動かすビジョナリー",
      resultTitle: "あなたは「理想ドラゴン」",
      resultLead: "その理想は、未来を変える大きな力になります。",
      colorMain: "#880e4f",
      colorSub: "#ad1457",
      image: "dragon.png",
      ogpImage: "ogp_dragon.png",
    },
    {
      id: "phoenix",
      name: "独立フェニックス",
      emoji: "🔥",
      axes: { mamoru:false, ronri:false, keikaku:false, anshin:true },
      axisLabel: "増やす・直感・挑戦・安心",
      catchcopy: "何度でも立ち上がる再生者",
      subcopy: "逆境を力に変える挑戦者",
      summary: "失敗を成長に変えるタイプ",
      description: "あなたは壁にぶつかっても、何度でも立ち上がる強さを持っています。失敗を経験として受け止め、前へ進む姿勢は大きな魅力です。",
      forYou: "あなたの経験は、必ず未来の力になります。",
      money: "お金は挑戦するための武器",
      work: "変化の多い環境で力を発揮する",
      love: "苦楽を共にできる相手を求める",
      strengths: ["回復力", "粘り強さ", "行動力"],
      weaknesses: ["頑張りすぎる", "無理をしやすい"],
      failures: "休まず走り続ける",
      growth: "立ち止まる勇気を持つ",
      stress: "全部自分で抱え込む",
      successReason: "逆境に強い",
      failureScene: "勢いで無理をしやすい",
      goodMatch: "革命ユニコーン",
      goodMatchReason: "挑戦する価値観を共有できる",
      badMatch: "悠々ペンギン",
      badMatchReason: "安定志向に物足りなさを感じる",
      message: "失敗は、あなたを強くする経験です。",
      luckyAction: "一日ゆっくり休む",
      luckyColor: "クリムゾン",
      luckyItem: "ランニングシューズ",
      snsText: "私は「独立フェニックス🔥」でした！",
      ogpCatch: "逆境を超えるチャレンジャー",
      resultTitle: "あなたは「独立フェニックス」",
      resultLead: "何度でも立ち上がる強さが、あなたの武器です。",
      colorMain: "#b71c1c",
      colorSub: "#d32f2f",
      image: "phoenix.png",
      ogpImage: "ogp_phoenix.png",
    },
    {
      id: "unicorn",
      name: "革命ユニコーン",
      emoji: "🦄",
      axes: { mamoru:false, ronri:false, keikaku:false, anshin:false },
      axisLabel: "増やす・直感・挑戦・自由",
      catchcopy: "常識を塗り替える革新者",
      subcopy: "誰も見たことのない未来を描く人",
      summary: "世界を変える可能性を持つタイプ",
      description: "あなたは人と同じ道よりも、自分だけの道を選びたいタイプです。新しい価値観やアイデアを生み出し、未来を変える力を持っています。理解されなくても、自分を信じて進める人です。",
      forYou: "あなたの個性は、新しい時代を作る力になります。",
      money: "お金は未来を創るための手段",
      work: "新しい価値を生み出す仕事で輝く",
      love: "唯一無二の関係を求める",
      strengths: ["独創性", "先見性", "行動力"],
      weaknesses: ["理解されにくい", "飽きっぽい"],
      failures: "常識を壊しすぎる",
      growth: "仲間を見つける",
      stress: "孤独を感じやすい",
      successReason: "新しい市場を見つけやすい",
      failureScene: "周囲とのズレが生まれやすい",
      goodMatch: "独立フェニックス",
      goodMatchReason: "新しい未来を一緒に描ける",
      badMatch: "資産防衛タートル",
      badMatchReason: "価値観の違いが大きい",
      message: "あなたにしか見えない未来があります。",
      luckyAction: "新しいアイデアを書き残す",
      luckyColor: "シルバー",
      luckyItem: "デジタルガジェット",
      snsText: "私は「革命ユニコーン🦄」でした！",
      ogpCatch: "未来を創るイノベーター",
      resultTitle: "あなたは「革命ユニコーン」",
      resultLead: "あなたの発想は、世界を変える可能性を秘めています。",
      colorMain: "#616161",
      colorSub: "#757575",
      image: "unicorn.png",
      ogpImage: "ogp_unicorn.png",
    },
  ],

  // タイプIDからオブジェクトを引くユーティリティ
  getType(id) {
    return this.types.find(t => t.id === id);
  },

  getTypeByName(name) {
    return this.types.find(t => t.name === name);
  },

  // 4軸の組み合わせからタイプを決定
  getTypeByAxes(mamoru, ronri, keikaku, anshin) {
    return this.types.find(t =>
      t.axes.mamoru  === mamoru &&
      t.axes.ronri   === ronri  &&
      t.axes.keikaku === keikaku &&
      t.axes.anshin  === anshin
    );
  }
};
